### ISSUE TITLE
Multiline values are currently broken

### ISSUE THREAD

**Issue by cstruck** [kubepack/chart-doc-gen#31]
the go package `github.com/olekukonko/tablewriter` handles newlines in strings a bit weird. It creates new table rows for each newline.

This kills the preview for multiline yaml values e.g:

```
someKey: |
   this is a
   multiline
   value
```

because it creates a table looking like

| a             | b               | c            |
|-------------|---------------|-------------|
|someKey |                  | |             |
|                |                  | this is a  |
|                |                  | multiline |
|                |                  | value     |

instead of how the table should actually look like

| a             | b               | c            |
|-------------|---------------|-------------|
|someKey |                  | &#124;<br>this is a<br>multiline<br>value  |

**Comment by tamalsaha** [comment]
Fixed in https://github.com/kubepack/chart-doc-gen/pull/32
